@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!$COLOR_A_6 = "#03256C"
!$COLOR_A_7 = "#1768AC"
!$COLOR_A_5 = "#558776"
!$COLOR_A_5 = "#558776"
!$COLOR_A_4 = "#b35806"
!$COLOR_A_3 = "#e08214"
!$COLOR_A_2 = "#fdb863"
!$COLOR_A_1 = "#fee0b6"
!$COLOR_NEUTRAL = "#f7f7f7"
!$COLOR_B_1 = "#d8daeb"
!$COLOR_B_2 = "#b2abd2"
!$COLOR_B_3 = "#8073ac"
!$COLOR_B_4 = "#542788"
!$COLOR_B_5 = "#2d004b"
!$COLOR_B_6 = "#9B72AA" 
!$COLOR_REL_LINE = "#8073ac"
!$COLOR_REL_TEXT = "#8073ac"

AddElementTag("gigya_system",  $bgColor=$COLOR_B_6, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_B_6)
AddElementTag("client_system", $bgColor=$COLOR_B_4, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_B_4 )
AddElementTag("customer", $bgColor=$COLOR_A_6, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_A_6)
AddElementTag("employee", $bgColor=$COLOR_A_7, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_A_7)

'  Boundary(client_app, "Client Application"){
     Container(www, "Web Site", "Container: nginx", "Serves static website assets to customer", $tags="client_system")
    Container(spa, "SPA", "Container: ReactJS / JavaScript", "Runs application code in customer's browser", $tags="client_system")
    Container(shop, "Shopping App", "Container: Spring Boot / Java", "Exposes API for shopping and persists shopping cart state", $tags="client_system")

'}

  
  
'  Boundary(gigya, "Gigya Resources"){

    Container(um, "Gigya User Management", "Container: Https/ JSON", "Stores all of the core information about customers, accounts, rate, favorites etc.", $tags="gigya_system")
  '}

 
' Boundary(authz_b, "Gigya Authz"){

 '}

' Boundary(authz_n, "Gigya Authn"){
   Container(idp, "IDP Authentication ", "Container: Https/ OAuth", "External Providees,provides authentication and identifications", $tags="external_system")
    Container(gauth, "User AuthN", "Container: Https/ Json", "Exposes API that supports user registration and authentication", $tags="gigya_system")
    Container(goauth, "OAuth Service", "Container: Https/ OAuth", "Exposes API that provides tokens with information about the user identity and permissions", $tags="gigya_system")


'}

' Boundary(enduser, "Customers"){
  
    Person(customer, "Buyer", "A customer of the store, with personal accounts.", $tags="customer")
    Person(customer_2, "Customer", "A customer of the store, ask support for help", $tags="customer")
    Person(gm, "Group Manager", "A customer of the store, with personal accounts, allowed to mange a shopping group." , $tags="customer")
    Person(go, "Group Owner", "A customer of the store, with personal accounts, own a shopping group.", $tags="customer")
 
'}

' Boundary(employee, "Employees"){
 
    Person(role_expert, "Role Expert", "A business implementor of the application.", $tags="employee")
    Person(support, "Customer Support", "Support customer requests", $tags="employee")
 '}
 
!procedure GAuthN_Container($name)
Container($name, "User AuthN", "Container: Https/ Json", "Exposes API that supports user registration and authentication", $tags="gigya_system")
!endprocedure

!procedure GOAuth_Container($name)
    OAuth_Container($name , $tags="gigya_system")
!endprocedure

!procedure OAuth_Container($name, $t ="oauth_system")
    Container($name, "OAuth Service", "Container: Https/ OAuth", "Exposes API that provides tokens with information about the user identity and permissions", $tags=$t)
!endprocedure

!procedure EIDP_Container($name, $t ="external_oauth_system")
   Container($name, "IDP Authentication ", "Container: Https/ OAuth", "External Providees,provides authentication and identifications", $tags=$t")
!endprocedure

!procedure Spa_Container($name, $t ="client_system")
    Container($name, "SPA", "Container: ReactJS / JavaScript", "Runs application code in customer's browser", $tags= $t)
!endprocedure

!procedure Shop_Container($name, $t ="client_system")
    Container($name, "Shopping App", "Container: Spring Boot / Java", "Exposes API for shopping and persists shopping cart state", $tags=$t)
!endprocedure

!procedure Authenticate($persona, $system)
BiRel($persona, $system, "Authenticaticate") 
!endprocedure
 
  
!procedure Gigya_AuthN($persona)
Authenticate($persona, gauth) 
!endprocedure

@enduml
