@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include https://raw.githubusercontent.com/dinavinter/my_docs/main/diagrams/authz/actors.iuml
 '!include actors.iuml
 

title Authorization B2B Model   
HIDE_STEREOTYPE()

 
Rel(go, authz_b2b,"Update Group Policy", "Allow Rated users to view silver page")
Authenticate_Admin(go)

Rel(customer, app_system_silver, "View")
Authenticate_Customer(customer )


Rel(role_expert, invitation, "Invite Group Owner")
Rel_Neighbor(role_expert, authz, "Update Permissions", Allow owner to update group policy)
Authenticate_Customer(role_expert )

Rel(invitation, um, "Update Group") 

Rel(app_system_silver, authz_b2b, "authz")

Rel(um, authz, "Authorize") 
Rel(authz_b2b, um, "Get Account Attributes" , "User Rate, Group Role")
Rel(authz_b2b, authz, "Authorize Group Owner" , "Can Edit Group Policy")

Rel(service_system, um, "Rate User")
 
'group relation
'System(group, "Shopping Group") 
'Rel_L(customer, group, "belongs")
'Rel_Neighbor(gm, group, "mange")
' Rel_Neighbor(go, group, "own")

'group manager 
'Rel(go, authz_b2b,"Update Group Policy", "Allow Manger To view Members ")
'Rel(group_mng_app, accounts, "Get Accounts", "authz token")
'Rel(accounts, authz, "Authorize") 
'Rel(group_mng_app, authz_b2b, "authz")
'Rel(gm, group_mng_app, "View Group Members")
'BiRel(gm, auth_system, "Authentication Interactions" )
'Rel(go, invitation, "Invite Manger")
'Rel_R(invitation, gm, "Group Manager Invitation")  

'mail
'System_Ext(mail_system, "E-mail system", "Exchange e-mail system.")

'Rel_U(invitation, go, "Group Owner Invitation") 
'Rel_R(mail_system, go, "Group Owner Invitation") 
'Rel_U(invitation, mail_system, "Group Owner Invitation") 


SHOW_LEGEND()
hide @unlinked

@enduml