@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include https://raw.githubusercontent.com/dinavinter/my_docs/main/diagrams/authz/actors.iuml
 '!include actors.iuml


title Authorization B2B Model   
HIDE_STEREOTYPE()

 
Rel(gm, app_system, "View Group Members")
BiRel_L(gm, auth_system, "Authenticate" )

Rel_L(go, authz_b2b,"Update Group Policy", "Allow Manger To view Members\nAllow Rated users to view silver page")
Rel(go, invitation, "Invite Manger")
BiRel_U(go, auth_system, "Authenticate")


Rel(customer, app_system_silver, "View")
BiRel(customer, auth_system, "Authenticate")

Rel(app_system, um, "Get Accounts", "authz token")
Rel(app_system, authz_b2b, "authz")

Rel_U(role_expert, invitation, "Invite Owner")
Rel_L(role_expert, authz, "Update Permissions", Allow owner to update group policy)
Rel_Neighbor(role_expert, auth_admin, "Authenticate")

Rel(invitation, um, "Update Group") 
'Rel_L(invitation, go, "Group Owner Invitation") 
'Rel_R(invitation, gm, "Group Manager Invitation") 

Rel(app_system_silver, authz_b2b, "authz")

Rel_Neighbor(um, authz, "Authorize")


Rel(authz_b2b, um, "get account attributes")

Rel_U(support, um, "View Account Information")
 
Rel_Neighbor(support, auth_admin, "Authenticate")

Rel_Neighbor(customer_2, support, "call")

Rel_Neighbor(service_system, um, "Rate account")

'group relation
'System(group, "Shopping Group") 
'Rel_L(customer, group, "belongs")
'Rel_Neighbor(gm, group, "mange")
' Rel_Neighbor(go, group, "own")

SHOW_LEGEND()

@enduml