@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include https://raw.githubusercontent.com/dinavinter/my_docs/main/diagrams/authz/actors.iuml
 '!include actors.iuml

title Gigya Authorization Model   


 
Rel(customer, app_system, "Buy")
Rel(app_system, service_system, "Uses")
Authenticate_Customer(customer)
'Rel(auth_system, um, "Uses")
Rel(role_expert, authz, "Update Permissions")
Rel(support, um, "View Account Information")
'Rel_Neighbor(app_system, auth_system, "Authenticate", "session")
Rel(service_system, um, "Rate account")
Rel(um, authz, "Authorize")
Rel(customer_2, support, "call")
Authenticate_Admin(role_expert)
Authenticate_Admin(support, auth_admin)


SHOW_LEGEND()
hide @unlinked


@enduml
 