@startuml
partition "**process** Consumer Per WH" {

:Input Event;
:produce event|
:wake up consumer;
:Consumer (0...N);
split
 :read<
 :send>
 :commit>
split again
 :read<
 :should buffer} 
 :read<
 :should buffer} 
 :read< 
 :send>
 :commit>
 :read<
 :send>
 :commit>
split again
  :read<
  :send> 
  :error;
  :err := err + 1] 
  :Wait\\
  :read<

 split again
 :read<
 :send> 
 :error;
 :err = max}
 :send to fail>  
 :read next< 
end split
}


 @enduml
